# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AkurMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AkurMe
pod 'Firebase/Core'
pod 'FirebaseUI/Auth'
pod 'Firebase/Database'

pod 'FirebaseUI/Google'
pod 'FirebaseUI/Facebook'
pod 'FirebaseUI/Twitter'
pod 'FirebaseUI/Phone'

end
